name: Catch2 Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest -V
